#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rbenjami <rbenjami@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2013/11/20 09:49:07 by rbenjami          #+#    #+#              #
#    Updated: 2013/11/20 11:31:21 by rbenjami         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

SRC			=	classic/helpers/basics.c			\
				\
				classic/position/basics.c			\
				classic/position/advanced.c			\
				\
				classic/color/basics.c				\
				classic/color/advanced.c			\
				\
				classic/image/basics.c				\
				\
				classic/line/basics.c				\
				classic/line/advanced.c				\
				classic/line/complex.c				\
				\
				\
				tests/line/basics.c					\
				tests/line/advanced.c				\
				tests/line/complex.c				\
				\
				tests/image/basics.c				\
				\
				classic/3d/utils.c					\
				classic/3d/vector2f.c				\
				classic/3d/vector2f_add.c			\
				classic/3d/vector2f_sub.c			\
				classic/3d/vector2f_mul.c			\
				classic/3d/vector2f_div.c			\
				classic/3d/vector2f_pow.c			\
				classic/3d/vector2f_get.c			\
				classic/3d/vector2f_rotate.c		\
				classic/3d/vector3f.c				\
				classic/3d/vector3f_add.c			\
				classic/3d/vector3f_sub.c			\
				classic/3d/vector3f_mul.c			\
				classic/3d/vector3f_div.c			\
				classic/3d/vector3f_pow.c			\
				classic/3d/vector3f_get.c			\
				classic/3d/vector3f_rotate.c		\
				classic/3d/quaternion.c				\
				classic/3d/quaternion_mul.c			\
				classic/3d/quaternion_rot.c			\
				classic/3d/matrix4f.c				\
				classic/3d/matrix4f_rot.c			\
				classic/3d/matrix4f_init.c			\
				classic/3d/vertex.c					\
				classic/3d/transforms.c
